name: Release on MacOS

on:
  push:
    tags:
      - "*"
  # Allow manual trigger from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # MacOS x64 Standard builds
          - os: macos-13
            python-version: "3.9"
            c_compiler: gcc-14
            cxx_compiler: g++-14
            xcode_version: "15.2"
            tier: standard
            arch: cpu
            artifact_name: radarsimpy_macos_py3.9
          - os: macos-13
            python-version: "3.10"
            c_compiler: gcc-14
            cxx_compiler: g++-14
            xcode_version: "15.2"
            tier: standard
            arch: cpu
            artifact_name: radarsimpy_macos_py3.10
          - os: macos-13
            python-version: "3.11"
            c_compiler: gcc-14
            cxx_compiler: g++-14
            xcode_version: "15.2"
            tier: standard
            arch: cpu
            artifact_name: radarsimpy_macos_py3.11
          - os: macos-13
            python-version: "3.12"
            c_compiler: gcc-14
            cxx_compiler: g++-14
            xcode_version: "15.2"
            tier: standard
            arch: cpu
            artifact_name: radarsimpy_macos_py3.12
          - os: macos-13
            python-version: "3.13"
            c_compiler: gcc-14
            cxx_compiler: g++-14
            xcode_version: "15.2"
            tier: standard
            arch: cpu
            artifact_name: radarsimpy_macos_py3.13
          # MacOS x64 Free Tier builds
          - os: macos-13
            python-version: "3.9"
            c_compiler: gcc-14
            cxx_compiler: g++-14
            xcode_version: "15.2"
            tier: free
            arch: cpu
            artifact_name: radarsimpy_macos_py3.9_freetier
          - os: macos-13
            python-version: "3.10"
            c_compiler: gcc-14
            cxx_compiler: g++-14
            xcode_version: "15.2"
            tier: free
            arch: cpu
            artifact_name: radarsimpy_macos_py3.10_freetier
          - os: macos-13
            python-version: "3.11"
            c_compiler: gcc-14
            cxx_compiler: g++-14
            xcode_version: "15.2"
            tier: free
            arch: cpu
            artifact_name: radarsimpy_macos_py3.11_freetier
          - os: macos-13
            python-version: "3.12"
            c_compiler: gcc-14
            cxx_compiler: g++-14
            xcode_version: "15.2"
            tier: free
            arch: cpu
            artifact_name: radarsimpy_macos_py3.12_freetier
          - os: macos-13
            python-version: "3.13"
            c_compiler: gcc-14
            cxx_compiler: g++-14
            xcode_version: "15.2"
            tier: free
            arch: cpu
            artifact_name: radarsimpy_macos_py3.13_freetier
          # MacOS ARM64 (Apple Silicon) Standard builds
          - os: macos-15
            python-version: "3.9"
            c_compiler: clang
            cxx_compiler: clang++
            xcode_version: "16.3"
            tier: standard
            arch: cpu
            artifact_name: radarsimpy_macos_arm_py3.9
          - os: macos-15
            python-version: "3.10"
            c_compiler: clang
            cxx_compiler: clang++
            xcode_version: "16.3"
            tier: standard
            arch: cpu
            artifact_name: radarsimpy_macos_arm_py3.10
          - os: macos-15
            python-version: "3.11"
            c_compiler: clang
            cxx_compiler: clang++
            xcode_version: "16.3"
            tier: standard
            arch: cpu
            artifact_name: radarsimpy_macos_arm_py3.11
          - os: macos-15
            python-version: "3.12"
            c_compiler: clang
            cxx_compiler: clang++
            xcode_version: "16.3"
            tier: standard
            arch: cpu
            artifact_name: radarsimpy_macos_arm_py3.12
          - os: macos-15
            python-version: "3.13"
            c_compiler: clang
            cxx_compiler: clang++
            xcode_version: "16.3"
            tier: standard
            arch: cpu
            artifact_name: radarsimpy_macos_arm_py3.13
          # MacOS ARM64 (Apple Silicon) Free Tier builds
          - os: macos-15
            python-version: "3.9"
            c_compiler: clang
            cxx_compiler: clang++
            xcode_version: "16.3"
            tier: free
            arch: cpu
            artifact_name: radarsimpy_macos_arm_py3.9_freetier
          - os: macos-15
            python-version: "3.10"
            c_compiler: clang
            cxx_compiler: clang++
            xcode_version: "16.3"
            tier: free
            arch: cpu
            artifact_name: radarsimpy_macos_arm_py3.10_freetier
          - os: macos-15
            python-version: "3.11"
            c_compiler: clang
            cxx_compiler: clang++
            xcode_version: "16.3"
            tier: free
            arch: cpu
            artifact_name: radarsimpy_macos_arm_py3.11_freetier
          - os: macos-15
            python-version: "3.12"
            c_compiler: clang
            cxx_compiler: clang++
            xcode_version: "16.3"
            tier: free
            arch: cpu
            artifact_name: radarsimpy_macos_arm_py3.12_freetier
          - os: macos-15
            python-version: "3.13"
            c_compiler: clang
            cxx_compiler: clang++
            xcode_version: "16.3"
            tier: free
            arch: cpu
            artifact_name: radarsimpy_macos_arm_py3.13_freetier

    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{secrets.RADARSIMC}}
          submodules: recursive
      
      - uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: ${{ matrix.xcode_version }}
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Build
        env:
          CC: ${{ matrix.c_compiler }}
          CXX: ${{ matrix.cxx_compiler }}
        run: |
          chmod +x build.sh
          ./build.sh --tier=${{ matrix.tier }} --arch=${{ matrix.arch }} --test=off
      
      - name: Archive built module
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: ${{ matrix.artifact_name }}
          path: ./radarsimpy
